version: '3.9'

services:
  web:
    build:
      context: ./services/web
      dockerfile: Dockerfile.2
    command: gunicorn --bind 0.0.0.0:5000 jdzred:app
    volumes:
      - static_volume:/home/app/web/app/static
      - media_volume:/home/app/web/app/media
    ports:
      - "5000"
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
    networks:
      - app_network

  db:
    image: postgres
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
    networks:
      - app_network

  nginx:
    build: 
      context: ./services/nginx
      dockerfile: Dockerfile.2
    volumes:
      - static_volume:/home/app/web/app/static
      - media_volume:/home/app/web/app/media
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - app_network

  redis:
    image: redis
    networks:
      - app_network

volumes:
  postgres_data_prod:
  static_volume:
  media_volume:

networks:
  app_network:
    driver: bridge
