FROM python:3.9-slim

# Install system dependencies and clean up to reduce image size
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    build-essential \
    python3-dev \
    libffi-dev \
    libssl-dev && \
    rm -rf /var/lib/apt/lists/*

# Upgrade pip and install Python packages
RUN pip install --upgrade pip setuptools wheel

# Copy requirements and install Python packages
COPY requirements.txt .
RUN pip install -r requirements.txt

# Install additional packages
RUN pip install gunicorn pymysql cryptography

# Copy application code
COPY app/ app/

#COPY app/static /home/app/web/app/static
#COPY app/media /home/app/web/app/media
COPY migrations/ migrations/
COPY jdzred.py config.py boot.sh ./

# Ensure the boot script is executable
RUN chmod +x boot.sh

# Set environment variables
ENV FLASK_APP=jdzred.py

# Expose port 5000
EXPOSE 5000

# Define the entry point
ENTRYPOINT ["./boot.sh"]


